// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: v1/user/session.proto

package user

import (
	common "gct/docs/protobuf/genproto/v1/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionDeviceType represents the type of device
type SessionDeviceType int32

const (
	SessionDeviceType_DEVICE_TYPE_UNSPECIFIED SessionDeviceType = 0
	SessionDeviceType_DEVICE_TYPE_DESKTOP     SessionDeviceType = 1
	SessionDeviceType_DEVICE_TYPE_MOBILE      SessionDeviceType = 2
	SessionDeviceType_DEVICE_TYPE_TABLET      SessionDeviceType = 3
	SessionDeviceType_DEVICE_TYPE_BOT         SessionDeviceType = 4
	SessionDeviceType_DEVICE_TYPE_TV          SessionDeviceType = 5
)

// Enum value maps for SessionDeviceType.
var (
	SessionDeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_DESKTOP",
		2: "DEVICE_TYPE_MOBILE",
		3: "DEVICE_TYPE_TABLET",
		4: "DEVICE_TYPE_BOT",
		5: "DEVICE_TYPE_TV",
	}
	SessionDeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_DESKTOP":     1,
		"DEVICE_TYPE_MOBILE":      2,
		"DEVICE_TYPE_TABLET":      3,
		"DEVICE_TYPE_BOT":         4,
		"DEVICE_TYPE_TV":          5,
	}
)

func (x SessionDeviceType) Enum() *SessionDeviceType {
	p := new(SessionDeviceType)
	*p = x
	return p
}

func (x SessionDeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionDeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_user_session_proto_enumTypes[0].Descriptor()
}

func (SessionDeviceType) Type() protoreflect.EnumType {
	return &file_v1_user_session_proto_enumTypes[0]
}

func (x SessionDeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionDeviceType.Descriptor instead.
func (SessionDeviceType) EnumDescriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{0}
}

// Session represents a user session
type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	DeviceId         string                 `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId"`
	DeviceName       *string                `protobuf:"bytes,3,opt,name=deviceName,proto3,oneof" json:"deviceName"`
	DeviceType       SessionDeviceType      `protobuf:"varint,4,opt,name=deviceType,proto3,enum=grpc.v1.SessionDeviceType" json:"deviceType"`
	IpAddress        *string                `protobuf:"bytes,5,opt,name=ipAddress,proto3,oneof" json:"ipAddress"`
	UserAgent        *string                `protobuf:"bytes,6,opt,name=userAgent,proto3,oneof" json:"userAgent"`
	FcmToken         *string                `protobuf:"bytes,7,opt,name=fcmToken,proto3,oneof" json:"fcmToken"`
	UserId           int64                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId"`
	CompanyId        int64                  `protobuf:"varint,9,opt,name=companyId,proto3" json:"companyId"`
	RefreshTokenHash string                 `protobuf:"bytes,10,opt,name=refreshTokenHash,proto3" json:"refreshTokenHash"` // Only used in internal communication
	ExpiresAt        int64                  `protobuf:"varint,11,opt,name=expiresAt,proto3" json:"expiresAt"`
	LastActivity     int64                  `protobuf:"varint,12,opt,name=lastActivity,proto3" json:"lastActivity"`
	Revoked          bool                   `protobuf:"varint,13,opt,name=revoked,proto3" json:"revoked"`
	CreatedAt        int64                  `protobuf:"varint,14,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt        int64                  `protobuf:"varint,15,opt,name=updatedAt,proto3" json:"updatedAt"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_v1_user_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Session) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *Session) GetDeviceType() SessionDeviceType {
	if x != nil {
		return x.DeviceType
	}
	return SessionDeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *Session) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *Session) GetFcmToken() string {
	if x != nil && x.FcmToken != nil {
		return *x.FcmToken
	}
	return ""
}

func (x *Session) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Session) GetRefreshTokenHash() string {
	if x != nil {
		return x.RefreshTokenHash
	}
	return ""
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Session) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *Session) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// SessionFilter represents a filter for session queries
type SessionFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id"`
	UserId        *int64                 `protobuf:"varint,2,opt,name=userId,proto3,oneof" json:"userId"`
	Revoked       *bool                  `protobuf:"varint,3,opt,name=revoked,proto3,oneof" json:"revoked"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFilter) Reset() {
	*x = SessionFilter{}
	mi := &file_v1_user_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFilter) ProtoMessage() {}

func (x *SessionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFilter.ProtoReflect.Descriptor instead.
func (*SessionFilter) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionFilter) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SessionFilter) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SessionFilter) GetRevoked() bool {
	if x != nil && x.Revoked != nil {
		return *x.Revoked
	}
	return false
}

// SessionsFilter represents a filter for multiple sessions with pagination
type SessionsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionFilter *SessionFilter         `protobuf:"bytes,1,opt,name=sessionFilter,proto3" json:"sessionFilter"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsFilter) Reset() {
	*x = SessionsFilter{}
	mi := &file_v1_user_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsFilter) ProtoMessage() {}

func (x *SessionsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsFilter.ProtoReflect.Descriptor instead.
func (*SessionsFilter) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionsFilter) GetSessionFilter() *SessionFilter {
	if x != nil {
		return x.SessionFilter
	}
	return nil
}

func (x *SessionsFilter) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SessionCreateRequest represents a request to create a session
type SessionCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId"`
	DeviceName    *string                `protobuf:"bytes,2,opt,name=deviceName,proto3,oneof" json:"deviceName"`
	DeviceType    SessionDeviceType      `protobuf:"varint,3,opt,name=deviceType,proto3,enum=grpc.v1.SessionDeviceType" json:"deviceType"`
	IpAddress     *string                `protobuf:"bytes,4,opt,name=ipAddress,proto3,oneof" json:"ipAddress"`
	UserAgent     *string                `protobuf:"bytes,5,opt,name=userAgent,proto3,oneof" json:"userAgent"`
	FcmToken      *string                `protobuf:"bytes,6,opt,name=fcmToken,proto3,oneof" json:"fcmToken"`
	UserId        int64                  `protobuf:"varint,7,opt,name=userId,proto3" json:"userId"`
	CompanyId     int64                  `protobuf:"varint,8,opt,name=companyId,proto3" json:"companyId"`
	ExpiresAt     int64                  `protobuf:"varint,9,opt,name=expiresAt,proto3" json:"expiresAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateRequest) Reset() {
	*x = SessionCreateRequest{}
	mi := &file_v1_user_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateRequest) ProtoMessage() {}

func (x *SessionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateRequest.ProtoReflect.Descriptor instead.
func (*SessionCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{3}
}

func (x *SessionCreateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionCreateRequest) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *SessionCreateRequest) GetDeviceType() SessionDeviceType {
	if x != nil {
		return x.DeviceType
	}
	return SessionDeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *SessionCreateRequest) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *SessionCreateRequest) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *SessionCreateRequest) GetFcmToken() string {
	if x != nil && x.FcmToken != nil {
		return *x.FcmToken
	}
	return ""
}

func (x *SessionCreateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SessionCreateRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *SessionCreateRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// SessionUpdateRequest represents a request to update a session
type SessionUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	DeviceName    *string                `protobuf:"bytes,2,opt,name=deviceName,proto3,oneof" json:"deviceName"`
	DeviceType    *SessionDeviceType     `protobuf:"varint,3,opt,name=deviceType,proto3,enum=grpc.v1.SessionDeviceType,oneof" json:"deviceType"`
	IpAddress     *string                `protobuf:"bytes,4,opt,name=ipAddress,proto3,oneof" json:"ipAddress"`
	UserAgent     *string                `protobuf:"bytes,5,opt,name=userAgent,proto3,oneof" json:"userAgent"`
	FcmToken      *string                `protobuf:"bytes,6,opt,name=fcmToken,proto3,oneof" json:"fcmToken"`
	ExpiresAt     *int64                 `protobuf:"varint,7,opt,name=expiresAt,proto3,oneof" json:"expiresAt"`
	LastActivity  *int64                 `protobuf:"varint,8,opt,name=lastActivity,proto3,oneof" json:"lastActivity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUpdateRequest) Reset() {
	*x = SessionUpdateRequest{}
	mi := &file_v1_user_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUpdateRequest) ProtoMessage() {}

func (x *SessionUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUpdateRequest.ProtoReflect.Descriptor instead.
func (*SessionUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{4}
}

func (x *SessionUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionUpdateRequest) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *SessionUpdateRequest) GetDeviceType() SessionDeviceType {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return SessionDeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *SessionUpdateRequest) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *SessionUpdateRequest) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *SessionUpdateRequest) GetFcmToken() string {
	if x != nil && x.FcmToken != nil {
		return *x.FcmToken
	}
	return ""
}

func (x *SessionUpdateRequest) GetExpiresAt() int64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *SessionUpdateRequest) GetLastActivity() int64 {
	if x != nil && x.LastActivity != nil {
		return *x.LastActivity
	}
	return 0
}

// SessionResponse represents a session response
type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_v1_user_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{5}
}

func (x *SessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

// SessionsResponse represents multiple sessions response
type SessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsResponse) Reset() {
	*x = SessionsResponse{}
	mi := &file_v1_user_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsResponse) ProtoMessage() {}

func (x *SessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsResponse.ProtoReflect.Descriptor instead.
func (*SessionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{6}
}

func (x *SessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SessionsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SessionRevokeRequest represents a request to revoke sessions
type SessionRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *string                `protobuf:"bytes,1,opt,name=sessionId,proto3,oneof" json:"sessionId"`
	UserId        *int64                 `protobuf:"varint,2,opt,name=userId,proto3,oneof" json:"userId"`
	RevokeAll     bool                   `protobuf:"varint,3,opt,name=revokeAll,proto3" json:"revokeAll"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRevokeRequest) Reset() {
	*x = SessionRevokeRequest{}
	mi := &file_v1_user_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRevokeRequest) ProtoMessage() {}

func (x *SessionRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRevokeRequest.ProtoReflect.Descriptor instead.
func (*SessionRevokeRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{7}
}

func (x *SessionRevokeRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SessionRevokeRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SessionRevokeRequest) GetRevokeAll() bool {
	if x != nil {
		return x.RevokeAll
	}
	return false
}

// SessionRevokeResponse represents revoke session response
type SessionRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RevokedCount  int64                  `protobuf:"varint,3,opt,name=revokedCount,proto3" json:"revokedCount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRevokeResponse) Reset() {
	*x = SessionRevokeResponse{}
	mi := &file_v1_user_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRevokeResponse) ProtoMessage() {}

func (x *SessionRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRevokeResponse.ProtoReflect.Descriptor instead.
func (*SessionRevokeResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_session_proto_rawDescGZIP(), []int{8}
}

func (x *SessionRevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SessionRevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SessionRevokeResponse) GetRevokedCount() int64 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

var File_v1_user_session_proto protoreflect.FileDescriptor

const file_v1_user_session_proto_rawDesc = "" +
	"\n" +
	"\x15v1/user/session.proto\x12\agrpc.v1\x1a\x1av1/common/pagination.proto\"\xaf\x04\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x01(\tR\bdeviceId\x12#\n" +
	"\n" +
	"deviceName\x18\x03 \x01(\tH\x00R\n" +
	"deviceName\x88\x01\x01\x12:\n" +
	"\n" +
	"deviceType\x18\x04 \x01(\x0e2\x1a.grpc.v1.SessionDeviceTypeR\n" +
	"deviceType\x12!\n" +
	"\tipAddress\x18\x05 \x01(\tH\x01R\tipAddress\x88\x01\x01\x12!\n" +
	"\tuserAgent\x18\x06 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12\x1f\n" +
	"\bfcmToken\x18\a \x01(\tH\x03R\bfcmToken\x88\x01\x01\x12\x16\n" +
	"\x06userId\x18\b \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcompanyId\x18\t \x01(\x03R\tcompanyId\x12*\n" +
	"\x10refreshTokenHash\x18\n" +
	" \x01(\tR\x10refreshTokenHash\x12\x1c\n" +
	"\texpiresAt\x18\v \x01(\x03R\texpiresAt\x12\"\n" +
	"\flastActivity\x18\f \x01(\x03R\flastActivity\x12\x18\n" +
	"\arevoked\x18\r \x01(\bR\arevoked\x12\x1c\n" +
	"\tcreatedAt\x18\x0e \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0f \x01(\x03R\tupdatedAtB\r\n" +
	"\v_deviceNameB\f\n" +
	"\n" +
	"_ipAddressB\f\n" +
	"\n" +
	"_userAgentB\v\n" +
	"\t_fcmToken\"~\n" +
	"\rSessionFilter\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1b\n" +
	"\x06userId\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x1d\n" +
	"\arevoked\x18\x03 \x01(\bH\x02R\arevoked\x88\x01\x01B\x05\n" +
	"\x03_idB\t\n" +
	"\a_userIdB\n" +
	"\n" +
	"\b_revoked\"\x83\x01\n" +
	"\x0eSessionsFilter\x12<\n" +
	"\rsessionFilter\x18\x01 \x01(\v2\x16.grpc.v1.SessionFilterR\rsessionFilter\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.grpc.v1.PaginationR\n" +
	"pagination\"\x86\x03\n" +
	"\x14SessionCreateRequest\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12#\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tH\x00R\n" +
	"deviceName\x88\x01\x01\x12:\n" +
	"\n" +
	"deviceType\x18\x03 \x01(\x0e2\x1a.grpc.v1.SessionDeviceTypeR\n" +
	"deviceType\x12!\n" +
	"\tipAddress\x18\x04 \x01(\tH\x01R\tipAddress\x88\x01\x01\x12!\n" +
	"\tuserAgent\x18\x05 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12\x1f\n" +
	"\bfcmToken\x18\x06 \x01(\tH\x03R\bfcmToken\x88\x01\x01\x12\x16\n" +
	"\x06userId\x18\a \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcompanyId\x18\b \x01(\x03R\tcompanyId\x12\x1c\n" +
	"\texpiresAt\x18\t \x01(\x03R\texpiresAtB\r\n" +
	"\v_deviceNameB\f\n" +
	"\n" +
	"_ipAddressB\f\n" +
	"\n" +
	"_userAgentB\v\n" +
	"\t_fcmToken\"\xa5\x03\n" +
	"\x14SessionUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tH\x00R\n" +
	"deviceName\x88\x01\x01\x12?\n" +
	"\n" +
	"deviceType\x18\x03 \x01(\x0e2\x1a.grpc.v1.SessionDeviceTypeH\x01R\n" +
	"deviceType\x88\x01\x01\x12!\n" +
	"\tipAddress\x18\x04 \x01(\tH\x02R\tipAddress\x88\x01\x01\x12!\n" +
	"\tuserAgent\x18\x05 \x01(\tH\x03R\tuserAgent\x88\x01\x01\x12\x1f\n" +
	"\bfcmToken\x18\x06 \x01(\tH\x04R\bfcmToken\x88\x01\x01\x12!\n" +
	"\texpiresAt\x18\a \x01(\x03H\x05R\texpiresAt\x88\x01\x01\x12'\n" +
	"\flastActivity\x18\b \x01(\x03H\x06R\flastActivity\x88\x01\x01B\r\n" +
	"\v_deviceNameB\r\n" +
	"\v_deviceTypeB\f\n" +
	"\n" +
	"_ipAddressB\f\n" +
	"\n" +
	"_userAgentB\v\n" +
	"\t_fcmTokenB\f\n" +
	"\n" +
	"_expiresAtB\x0f\n" +
	"\r_lastActivity\"=\n" +
	"\x0fSessionResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.grpc.v1.SessionR\asession\"u\n" +
	"\x10SessionsResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.grpc.v1.SessionR\bsessions\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.grpc.v1.PaginationR\n" +
	"pagination\"\x8d\x01\n" +
	"\x14SessionRevokeRequest\x12!\n" +
	"\tsessionId\x18\x01 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1b\n" +
	"\x06userId\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x1c\n" +
	"\trevokeAll\x18\x03 \x01(\bR\trevokeAllB\f\n" +
	"\n" +
	"_sessionIdB\t\n" +
	"\a_userId\"o\n" +
	"\x15SessionRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\frevokedCount\x18\x03 \x01(\x03R\frevokedCount*\xa2\x01\n" +
	"\x11SessionDeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEVICE_TYPE_DESKTOP\x10\x01\x12\x16\n" +
	"\x12DEVICE_TYPE_MOBILE\x10\x02\x12\x16\n" +
	"\x12DEVICE_TYPE_TABLET\x10\x03\x12\x13\n" +
	"\x0fDEVICE_TYPE_BOT\x10\x04\x12\x12\n" +
	"\x0eDEVICE_TYPE_TV\x10\x052\xfe\x03\n" +
	"\x0eSessionService\x12H\n" +
	"\rCreateSession\x12\x1d.grpc.v1.SessionCreateRequest\x1a\x18.grpc.v1.SessionResponse\x12>\n" +
	"\n" +
	"GetSession\x12\x16.grpc.v1.SessionFilter\x1a\x18.grpc.v1.SessionResponse\x12A\n" +
	"\vGetSessions\x12\x17.grpc.v1.SessionsFilter\x1a\x19.grpc.v1.SessionsResponse\x12H\n" +
	"\rUpdateSession\x12\x1d.grpc.v1.SessionUpdateRequest\x1a\x18.grpc.v1.SessionResponse\x12A\n" +
	"\rDeleteSession\x12\x16.grpc.v1.SessionFilter\x1a\x18.grpc.v1.SessionResponse\x12N\n" +
	"\rRevokeSession\x12\x1d.grpc.v1.SessionRevokeRequest\x1a\x1e.grpc.v1.SessionRevokeResponse\x12B\n" +
	"\x0eUpdateActivity\x12\x16.grpc.v1.SessionFilter\x1a\x18.grpc.v1.SessionResponseB$Z\"gct/docs/protobuf/genproto/v1/userb\x06proto3"

var (
	file_v1_user_session_proto_rawDescOnce sync.Once
	file_v1_user_session_proto_rawDescData []byte
)

func file_v1_user_session_proto_rawDescGZIP() []byte {
	file_v1_user_session_proto_rawDescOnce.Do(func() {
		file_v1_user_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_session_proto_rawDesc), len(file_v1_user_session_proto_rawDesc)))
	})
	return file_v1_user_session_proto_rawDescData
}

var file_v1_user_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_user_session_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_user_session_proto_goTypes = []any{
	(SessionDeviceType)(0),        // 0: grpc.v1.SessionDeviceType
	(*Session)(nil),               // 1: grpc.v1.Session
	(*SessionFilter)(nil),         // 2: grpc.v1.SessionFilter
	(*SessionsFilter)(nil),        // 3: grpc.v1.SessionsFilter
	(*SessionCreateRequest)(nil),  // 4: grpc.v1.SessionCreateRequest
	(*SessionUpdateRequest)(nil),  // 5: grpc.v1.SessionUpdateRequest
	(*SessionResponse)(nil),       // 6: grpc.v1.SessionResponse
	(*SessionsResponse)(nil),      // 7: grpc.v1.SessionsResponse
	(*SessionRevokeRequest)(nil),  // 8: grpc.v1.SessionRevokeRequest
	(*SessionRevokeResponse)(nil), // 9: grpc.v1.SessionRevokeResponse
	(*common.Pagination)(nil),     // 10: grpc.v1.Pagination
}
var file_v1_user_session_proto_depIdxs = []int32{
	0,  // 0: grpc.v1.Session.deviceType:type_name -> grpc.v1.SessionDeviceType
	2,  // 1: grpc.v1.SessionsFilter.sessionFilter:type_name -> grpc.v1.SessionFilter
	10, // 2: grpc.v1.SessionsFilter.pagination:type_name -> grpc.v1.Pagination
	0,  // 3: grpc.v1.SessionCreateRequest.deviceType:type_name -> grpc.v1.SessionDeviceType
	0,  // 4: grpc.v1.SessionUpdateRequest.deviceType:type_name -> grpc.v1.SessionDeviceType
	1,  // 5: grpc.v1.SessionResponse.session:type_name -> grpc.v1.Session
	1,  // 6: grpc.v1.SessionsResponse.sessions:type_name -> grpc.v1.Session
	10, // 7: grpc.v1.SessionsResponse.pagination:type_name -> grpc.v1.Pagination
	4,  // 8: grpc.v1.SessionService.CreateSession:input_type -> grpc.v1.SessionCreateRequest
	2,  // 9: grpc.v1.SessionService.GetSession:input_type -> grpc.v1.SessionFilter
	3,  // 10: grpc.v1.SessionService.GetSessions:input_type -> grpc.v1.SessionsFilter
	5,  // 11: grpc.v1.SessionService.UpdateSession:input_type -> grpc.v1.SessionUpdateRequest
	2,  // 12: grpc.v1.SessionService.DeleteSession:input_type -> grpc.v1.SessionFilter
	8,  // 13: grpc.v1.SessionService.RevokeSession:input_type -> grpc.v1.SessionRevokeRequest
	2,  // 14: grpc.v1.SessionService.UpdateActivity:input_type -> grpc.v1.SessionFilter
	6,  // 15: grpc.v1.SessionService.CreateSession:output_type -> grpc.v1.SessionResponse
	6,  // 16: grpc.v1.SessionService.GetSession:output_type -> grpc.v1.SessionResponse
	7,  // 17: grpc.v1.SessionService.GetSessions:output_type -> grpc.v1.SessionsResponse
	6,  // 18: grpc.v1.SessionService.UpdateSession:output_type -> grpc.v1.SessionResponse
	6,  // 19: grpc.v1.SessionService.DeleteSession:output_type -> grpc.v1.SessionResponse
	9,  // 20: grpc.v1.SessionService.RevokeSession:output_type -> grpc.v1.SessionRevokeResponse
	6,  // 21: grpc.v1.SessionService.UpdateActivity:output_type -> grpc.v1.SessionResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_user_session_proto_init() }
func file_v1_user_session_proto_init() {
	if File_v1_user_session_proto != nil {
		return
	}
	file_v1_user_session_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_user_session_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_user_session_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_user_session_proto_msgTypes[4].OneofWrappers = []any{}
	file_v1_user_session_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_session_proto_rawDesc), len(file_v1_user_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_session_proto_goTypes,
		DependencyIndexes: file_v1_user_session_proto_depIdxs,
		EnumInfos:         file_v1_user_session_proto_enumTypes,
		MessageInfos:      file_v1_user_session_proto_msgTypes,
	}.Build()
	File_v1_user_session_proto = out.File
	file_v1_user_session_proto_goTypes = nil
	file_v1_user_session_proto_depIdxs = nil
}
