// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: v1/user/user.proto

package user

import (
	common "gct/docs/protobuf/genproto/v1/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user entity
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone"`
	PasswordHash  string                 `protobuf:"bytes,4,opt,name=passwordHash,proto3" json:"passwordHash"` // Only used in internal communication
	Salt          *string                `protobuf:"bytes,5,opt,name=salt,proto3,oneof" json:"salt"`           // Only used in internal communication
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt"`
	DeletedAt     int64                  `protobuf:"varint,8,opt,name=deletedAt,proto3" json:"deletedAt"`
	LastSeen      *int64                 `protobuf:"varint,9,opt,name=lastSeen,proto3,oneof" json:"lastSeen"`
	Password      string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password"` // Only used for create/update operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetSalt() string {
	if x != nil && x.Salt != nil {
		return *x.Salt
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *User) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *User) GetLastSeen() int64 {
	if x != nil && x.LastSeen != nil {
		return *x.LastSeen
	}
	return 0
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UserFilter represents a filter for user queries
type UserFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id"`
	Phone         *string                `protobuf:"bytes,2,opt,name=phone,proto3,oneof" json:"phone"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilter) Reset() {
	*x = UserFilter{}
	mi := &file_v1_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilter) ProtoMessage() {}

func (x *UserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilter.ProtoReflect.Descriptor instead.
func (*UserFilter) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserFilter) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UserFilter) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

// UsersFilter represents a filter for multiple users with pagination
type UsersFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFilter    *UserFilter            `protobuf:"bytes,1,opt,name=userFilter,proto3" json:"userFilter"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersFilter) Reset() {
	*x = UsersFilter{}
	mi := &file_v1_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersFilter) ProtoMessage() {}

func (x *UsersFilter) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersFilter.ProtoReflect.Descriptor instead.
func (*UsersFilter) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UsersFilter) GetUserFilter() *UserFilter {
	if x != nil {
		return x.UserFilter
	}
	return nil
}

func (x *UsersFilter) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// UserCreateRequest represents a request to create a user
type UserCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_v1_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserCreateRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserCreateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UserUpdateRequest represents a request to update a user
type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone"`
	Password      *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_v1_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserUpdateRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserUpdateRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserUpdateRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// UserResponse represents a user response
type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_v1_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UsersResponse represents multiple users response
type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_v1_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// UserAuthRequest represents authentication request
type UserAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthRequest) Reset() {
	*x = UserAuthRequest{}
	mi := &file_v1_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthRequest) ProtoMessage() {}

func (x *UserAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthRequest.ProtoReflect.Descriptor instead.
func (*UserAuthRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserAuthRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UserAuthResponse represents authentication response
type UserAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthResponse) Reset() {
	*x = UserAuthResponse{}
	mi := &file_v1_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthResponse) ProtoMessage() {}

func (x *UserAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthResponse.ProtoReflect.Descriptor instead.
func (*UserAuthResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *UserAuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_user_user_proto protoreflect.FileDescriptor

const file_v1_user_user_proto_rawDesc = "" +
	"\n" +
	"\x12v1/user/user.proto\x12\agrpc.v1\x1a\x1av1/common/pagination.proto\"\xc4\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\"\n" +
	"\fpasswordHash\x18\x04 \x01(\tR\fpasswordHash\x12\x17\n" +
	"\x04salt\x18\x05 \x01(\tH\x01R\x04salt\x88\x01\x01\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\b \x01(\x03R\tdeletedAt\x12\x1f\n" +
	"\blastSeen\x18\t \x01(\x03H\x02R\blastSeen\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpasswordB\v\n" +
	"\t_usernameB\a\n" +
	"\x05_saltB\v\n" +
	"\t_lastSeen\"M\n" +
	"\n" +
	"UserFilter\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x02 \x01(\tH\x01R\x05phone\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_phone\"w\n" +
	"\vUsersFilter\x123\n" +
	"\n" +
	"userFilter\x18\x01 \x01(\v2\x13.grpc.v1.UserFilterR\n" +
	"userFilter\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.grpc.v1.PaginationR\n" +
	"pagination\"s\n" +
	"\x11UserCreateRequest\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x88\x01\x01\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordB\v\n" +
	"\t_username\"\xa4\x01\n" +
	"\x11UserUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x02R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_phoneB\v\n" +
	"\t_password\"1\n" +
	"\fUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.grpc.v1.UserR\x04user\"i\n" +
	"\rUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.grpc.v1.UserR\x05users\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.grpc.v1.PaginationR\n" +
	"pagination\"C\n" +
	"\x0fUserAuthRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"{\n" +
	"\x10UserAuthResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\r.grpc.v1.UserR\x04user2\xb6\x03\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x1a.grpc.v1.UserCreateRequest\x1a\x15.grpc.v1.UserResponse\x125\n" +
	"\aGetUser\x12\x13.grpc.v1.UserFilter\x1a\x15.grpc.v1.UserResponse\x128\n" +
	"\bGetUsers\x12\x14.grpc.v1.UsersFilter\x1a\x16.grpc.v1.UsersResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x1a.grpc.v1.UserUpdateRequest\x1a\x15.grpc.v1.UserResponse\x128\n" +
	"\n" +
	"DeleteUser\x12\x13.grpc.v1.UserFilter\x1a\x15.grpc.v1.UserResponse\x12C\n" +
	"\fAuthenticate\x12\x18.grpc.v1.UserAuthRequest\x1a\x19.grpc.v1.UserAuthResponse\x125\n" +
	"\aSignOut\x12\x13.grpc.v1.UserFilter\x1a\x15.grpc.v1.UserResponseB$Z\"gct/docs/protobuf/genproto/v1/userb\x06proto3"

var (
	file_v1_user_user_proto_rawDescOnce sync.Once
	file_v1_user_user_proto_rawDescData []byte
)

func file_v1_user_user_proto_rawDescGZIP() []byte {
	file_v1_user_user_proto_rawDescOnce.Do(func() {
		file_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_user_proto_rawDesc), len(file_v1_user_user_proto_rawDesc)))
	})
	return file_v1_user_user_proto_rawDescData
}

var file_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_user_user_proto_goTypes = []any{
	(*User)(nil),              // 0: grpc.v1.User
	(*UserFilter)(nil),        // 1: grpc.v1.UserFilter
	(*UsersFilter)(nil),       // 2: grpc.v1.UsersFilter
	(*UserCreateRequest)(nil), // 3: grpc.v1.UserCreateRequest
	(*UserUpdateRequest)(nil), // 4: grpc.v1.UserUpdateRequest
	(*UserResponse)(nil),      // 5: grpc.v1.UserResponse
	(*UsersResponse)(nil),     // 6: grpc.v1.UsersResponse
	(*UserAuthRequest)(nil),   // 7: grpc.v1.UserAuthRequest
	(*UserAuthResponse)(nil),  // 8: grpc.v1.UserAuthResponse
	(*common.Pagination)(nil), // 9: grpc.v1.Pagination
}
var file_v1_user_user_proto_depIdxs = []int32{
	1,  // 0: grpc.v1.UsersFilter.userFilter:type_name -> grpc.v1.UserFilter
	9,  // 1: grpc.v1.UsersFilter.pagination:type_name -> grpc.v1.Pagination
	0,  // 2: grpc.v1.UserResponse.user:type_name -> grpc.v1.User
	0,  // 3: grpc.v1.UsersResponse.users:type_name -> grpc.v1.User
	9,  // 4: grpc.v1.UsersResponse.pagination:type_name -> grpc.v1.Pagination
	0,  // 5: grpc.v1.UserAuthResponse.user:type_name -> grpc.v1.User
	3,  // 6: grpc.v1.UserService.CreateUser:input_type -> grpc.v1.UserCreateRequest
	1,  // 7: grpc.v1.UserService.GetUser:input_type -> grpc.v1.UserFilter
	2,  // 8: grpc.v1.UserService.GetUsers:input_type -> grpc.v1.UsersFilter
	4,  // 9: grpc.v1.UserService.UpdateUser:input_type -> grpc.v1.UserUpdateRequest
	1,  // 10: grpc.v1.UserService.DeleteUser:input_type -> grpc.v1.UserFilter
	7,  // 11: grpc.v1.UserService.Authenticate:input_type -> grpc.v1.UserAuthRequest
	1,  // 12: grpc.v1.UserService.SignOut:input_type -> grpc.v1.UserFilter
	5,  // 13: grpc.v1.UserService.CreateUser:output_type -> grpc.v1.UserResponse
	5,  // 14: grpc.v1.UserService.GetUser:output_type -> grpc.v1.UserResponse
	6,  // 15: grpc.v1.UserService.GetUsers:output_type -> grpc.v1.UsersResponse
	5,  // 16: grpc.v1.UserService.UpdateUser:output_type -> grpc.v1.UserResponse
	5,  // 17: grpc.v1.UserService.DeleteUser:output_type -> grpc.v1.UserResponse
	8,  // 18: grpc.v1.UserService.Authenticate:output_type -> grpc.v1.UserAuthResponse
	5,  // 19: grpc.v1.UserService.SignOut:output_type -> grpc.v1.UserResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_user_user_proto_init() }
func file_v1_user_user_proto_init() {
	if File_v1_user_user_proto != nil {
		return
	}
	file_v1_user_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_user_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_user_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_user_user_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_user_proto_rawDesc), len(file_v1_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_user_proto_goTypes,
		DependencyIndexes: file_v1_user_user_proto_depIdxs,
		MessageInfos:      file_v1_user_user_proto_msgTypes,
	}.Build()
	File_v1_user_user_proto = out.File
	file_v1_user_user_proto_goTypes = nil
	file_v1_user_user_proto_depIdxs = nil
}
