// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Session struct {
	ID               string         `db:"id" json:"id"`
	UserID           int64          `db:"user_id" json:"user_id"`
	DeviceID         string         `db:"device_id" json:"device_id"`
	DeviceName       sql.NullString `db:"device_name" json:"device_name"`
	DeviceType       sql.NullString `db:"device_type" json:"device_type"`
	IpAddress        sql.NullString `db:"ip_address" json:"ip_address"`
	UserAgent        sql.NullString `db:"user_agent" json:"user_agent"`
	FcmToken         sql.NullString `db:"fcm_token" json:"fcm_token"`
	RefreshTokenHash sql.NullString `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        time.Time      `db:"expires_at" json:"expires_at"`
	LastActivity     time.Time      `db:"last_activity" json:"last_activity"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	Revoked          int64          `db:"revoked" json:"revoked"`
}

type User struct {
	ID           int64          `db:"id" json:"id"`
	Username     sql.NullString `db:"username" json:"username"`
	Phone        string         `db:"phone" json:"phone"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	Salt         sql.NullString `db:"salt" json:"salt"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullInt64  `db:"deleted_at" json:"deleted_at"`
	LastSeen     sql.NullTime   `db:"last_seen" json:"last_seen"`
}
