package middleware

import (
	"time"

	"gct/consts"
	"gct/internal/controller/restapi/util"
	"gct/pkg/logger"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// Logger returns a Gin middleware that logs standardized information about every HTTP request.
// It captures the request method, final path (including query string), status code, and latency.
// Logging is performed asynchronously to ensure minimal impact on the request processing time.
func Logger(l logger.Log) gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		path := c.Request.URL.Path
		raw := c.Request.URL.RawQuery

		// Execute the handler chain.
		c.Next()

		// Construct the full path with query parameters for detailed tracing.
		if raw != "" {
			path = path + "?" + raw
		}

		// Create a shallow copy of the Gin context for use in the background goroutine.
		// THIS IS CRITICAL: Gin recycles context objects. Accessing the original context in a
		// goroutine after c.Next() returns can lead to race conditions and data corruption.
		cp := c.Copy()

		// Retrieve the correlation ID generated by the RequestID middleware.
		// Uses GetString which returns empty string if key doesn't exist.
		requestID := c.GetString(consts.CtxKeyRequestID)

		// Dispatch logging to a separate goroutine.
		// This "fire-and-forget" approach prevents slow I/O (like disk writes or network log shipping)
		// from adding latency to the client's API response.
		go func() {
			l.Infow("HTTP request",
				zap.String(consts.CtxKeyRequestID, requestID),
				zap.String("method", cp.Request.Method),
				zap.String("path", path),
				zap.Int("status", cp.Writer.Status()),
				zap.String("latency", time.Since(start).String()),
				zap.String("client_ip", util.GetIPAddress(cp)),
				zap.String("error", cp.Errors.String()),
			)
		}()
	}
}
