// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditActionType string

const (
	AuditActionTypeLOGIN           AuditActionType = "LOGIN"
	AuditActionTypeLOGOUT          AuditActionType = "LOGOUT"
	AuditActionTypeSESSIONREVOKE   AuditActionType = "SESSION_REVOKE"
	AuditActionTypePASSWORDCHANGE  AuditActionType = "PASSWORD_CHANGE"
	AuditActionTypeMFAVERIFYFAIL   AuditActionType = "MFA_VERIFY_FAIL"
	AuditActionTypeACCESSGRANTED   AuditActionType = "ACCESS_GRANTED"
	AuditActionTypeACCESSDENIED    AuditActionType = "ACCESS_DENIED"
	AuditActionTypePOLICYMATCHED   AuditActionType = "POLICY_MATCHED"
	AuditActionTypePOLICYDENIED    AuditActionType = "POLICY_DENIED"
	AuditActionTypeUSERCREATE      AuditActionType = "USER_CREATE"
	AuditActionTypeUSERUPDATE      AuditActionType = "USER_UPDATE"
	AuditActionTypeUSERDELETE      AuditActionType = "USER_DELETE"
	AuditActionTypeROLEASSIGN      AuditActionType = "ROLE_ASSIGN"
	AuditActionTypeROLEREMOVE      AuditActionType = "ROLE_REMOVE"
	AuditActionTypeORDERAPPROVE    AuditActionType = "ORDER_APPROVE"
	AuditActionTypeORDERCANCEL     AuditActionType = "ORDER_CANCEL"
	AuditActionTypePAYMENTPROCESS  AuditActionType = "PAYMENT_PROCESS"
	AuditActionTypePAYMENTCANCEL   AuditActionType = "PAYMENT_CANCEL"
	AuditActionTypePOLICYEVALUATED AuditActionType = "POLICY_EVALUATED"
	AuditActionTypeADMINCHANGE     AuditActionType = "ADMIN_CHANGE"
)

func (e *AuditActionType) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditActionType(s)
	case string:
		*e = AuditActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditActionType: %T", src)
	}
	return nil
}

type NullAuditActionType struct {
	AuditActionType AuditActionType `json:"audit_action_type"`
	Valid           bool            `json:"valid"` // Valid is true if AuditActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditActionType) Scan(value any) error {
	if value == nil {
		ns.AuditActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditActionType), nil
}

type ErrorCategoryEnum string

const (
	ErrorCategoryEnumDATA       ErrorCategoryEnum = "DATA"
	ErrorCategoryEnumAUTH       ErrorCategoryEnum = "AUTH"
	ErrorCategoryEnumSYSTEM     ErrorCategoryEnum = "SYSTEM"
	ErrorCategoryEnumVALIDATION ErrorCategoryEnum = "VALIDATION"
	ErrorCategoryEnumBUSINESS   ErrorCategoryEnum = "BUSINESS"
	ErrorCategoryEnumUNKNOWN    ErrorCategoryEnum = "UNKNOWN"
)

func (e *ErrorCategoryEnum) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = ErrorCategoryEnum(s)
	case string:
		*e = ErrorCategoryEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ErrorCategoryEnum: %T", src)
	}
	return nil
}

type NullErrorCategoryEnum struct {
	ErrorCategoryEnum ErrorCategoryEnum `json:"error_category_enum"`
	Valid             bool              `json:"valid"` // Valid is true if ErrorCategoryEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullErrorCategoryEnum) Scan(value any) error {
	if value == nil {
		ns.ErrorCategoryEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ErrorCategoryEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullErrorCategoryEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ErrorCategoryEnum), nil
}

type ErrorSeverityEnum string

const (
	ErrorSeverityEnumLOW      ErrorSeverityEnum = "LOW"
	ErrorSeverityEnumMEDIUM   ErrorSeverityEnum = "MEDIUM"
	ErrorSeverityEnumHIGH     ErrorSeverityEnum = "HIGH"
	ErrorSeverityEnumCRITICAL ErrorSeverityEnum = "CRITICAL"
)

func (e *ErrorSeverityEnum) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = ErrorSeverityEnum(s)
	case string:
		*e = ErrorSeverityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ErrorSeverityEnum: %T", src)
	}
	return nil
}

type NullErrorSeverityEnum struct {
	ErrorSeverityEnum ErrorSeverityEnum `json:"error_severity_enum"`
	Valid             bool              `json:"valid"` // Valid is true if ErrorSeverityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullErrorSeverityEnum) Scan(value any) error {
	if value == nil {
		ns.ErrorSeverityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ErrorSeverityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullErrorSeverityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ErrorSeverityEnum), nil
}

type PolicyEffect string

const (
	PolicyEffectALLOW PolicyEffect = "ALLOW"
	PolicyEffectDENY  PolicyEffect = "DENY"
)

func (e *PolicyEffect) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = PolicyEffect(s)
	case string:
		*e = PolicyEffect(s)
	default:
		return fmt.Errorf("unsupported scan type for PolicyEffect: %T", src)
	}
	return nil
}

type NullPolicyEffect struct {
	PolicyEffect PolicyEffect `json:"policy_effect"`
	Valid        bool         `json:"valid"` // Valid is true if PolicyEffect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPolicyEffect) Scan(value any) error {
	if value == nil {
		ns.PolicyEffect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PolicyEffect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPolicyEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PolicyEffect), nil
}

type RelationTypes string

const (
	RelationTypesUNREVEALED RelationTypes = "UNREVEALED"
	RelationTypesBRANCH     RelationTypes = "BRANCH"
	RelationTypesREGION     RelationTypes = "REGION"
)

func (e *RelationTypes) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = RelationTypes(s)
	case string:
		*e = RelationTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for RelationTypes: %T", src)
	}
	return nil
}

type NullRelationTypes struct {
	RelationTypes RelationTypes `json:"relation_types"`
	Valid         bool          `json:"valid"` // Valid is true if RelationTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationTypes) Scan(value any) error {
	if value == nil {
		ns.RelationTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelationTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelationTypes), nil
}

type SessionDeviceType string

const (
	SessionDeviceTypeDESKTOP SessionDeviceType = "DESKTOP"
	SessionDeviceTypeMOBILE  SessionDeviceType = "MOBILE"
	SessionDeviceTypeTABLET  SessionDeviceType = "TABLET"
	SessionDeviceTypeBOT     SessionDeviceType = "BOT"
	SessionDeviceTypeTV      SessionDeviceType = "TV"
)

func (e *SessionDeviceType) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionDeviceType(s)
	case string:
		*e = SessionDeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionDeviceType: %T", src)
	}
	return nil
}

type NullSessionDeviceType struct {
	SessionDeviceType SessionDeviceType `json:"session_device_type"`
	Valid             bool              `json:"valid"` // Valid is true if SessionDeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionDeviceType) Scan(value any) error {
	if value == nil {
		ns.SessionDeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionDeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionDeviceType), nil
}

type AuditLog struct {
	ID           uuid.UUID             `db:"id" json:"id"`
	UserID       uuid.NullUUID         `db:"user_id" json:"user_id"`
	SessionID    uuid.NullUUID         `db:"session_id" json:"session_id"`
	Action       AuditActionType       `db:"action" json:"action"`
	ResourceType sql.NullString        `db:"resource_type" json:"resource_type"`
	ResourceID   uuid.NullUUID         `db:"resource_id" json:"resource_id"`
	Platform     sql.NullString        `db:"platform" json:"platform"`
	IpAddress    pqtype.Inet           `db:"ip_address" json:"ip_address"`
	UserAgent    sql.NullString        `db:"user_agent" json:"user_agent"`
	Permission   sql.NullString        `db:"permission" json:"permission"`
	PolicyID     uuid.NullUUID         `db:"policy_id" json:"policy_id"`
	Decision     sql.NullString        `db:"decision" json:"decision"`
	Success      bool                  `db:"success" json:"success"`
	ErrorMessage sql.NullString        `db:"error_message" json:"error_message"`
	Metadata     pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	CreatedAt    time.Time             `db:"created_at" json:"created_at"`
}

type EndpointHistory struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	UserID       uuid.NullUUID  `db:"user_id" json:"user_id"`
	SessionID    uuid.NullUUID  `db:"session_id" json:"session_id"`
	Method       string         `db:"method" json:"method"`
	Path         string         `db:"path" json:"path"`
	StatusCode   int16          `db:"status_code" json:"status_code"`
	DurationMs   int32          `db:"duration_ms" json:"duration_ms"`
	Platform     sql.NullString `db:"platform" json:"platform"`
	IpAddress    pqtype.Inet    `db:"ip_address" json:"ip_address"`
	UserAgent    sql.NullString `db:"user_agent" json:"user_agent"`
	Permission   sql.NullString `db:"permission" json:"permission"`
	Decision     sql.NullString `db:"decision" json:"decision"`
	RequestID    uuid.NullUUID  `db:"request_id" json:"request_id"`
	RateLimited  sql.NullBool   `db:"rate_limited" json:"rate_limited"`
	ResponseSize sql.NullInt32  `db:"response_size" json:"response_size"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

type ErrorCode struct {
	ID         uuid.UUID             `db:"id" json:"id"`
	Code       string                `db:"code" json:"code"`
	Message    string                `db:"message" json:"message"`
	HttpStatus int32                 `db:"http_status" json:"http_status"`
	Category   NullErrorCategoryEnum `db:"category" json:"category"`
	Severity   NullErrorSeverityEnum `db:"severity" json:"severity"`
	Retryable  sql.NullBool          `db:"retryable" json:"retryable"`
	RetryAfter sql.NullInt32         `db:"retry_after" json:"retry_after"`
	Suggestion sql.NullString        `db:"suggestion" json:"suggestion"`
	CreatedAt  time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time             `db:"updated_at" json:"updated_at"`
}

type FunctionMetric struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	Name       string         `db:"name" json:"name"`
	LatencyMs  int32          `db:"latency_ms" json:"latency_ms"`
	IsPanic    sql.NullBool   `db:"is_panic" json:"is_panic"`
	PanicError sql.NullString `db:"panic_error" json:"panic_error"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
}

type Permission struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	ParentID  uuid.NullUUID `db:"parent_id" json:"parent_id"`
	Name      string        `db:"name" json:"name"`
	CreatedAt sql.NullTime  `db:"created_at" json:"created_at"`
}

type PermissionScope struct {
	PermissionID uuid.UUID    `db:"permission_id" json:"permission_id"`
	Path         string       `db:"path" json:"path"`
	Method       string       `db:"method" json:"method"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
}

type Policy struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	PermissionID uuid.NullUUID   `db:"permission_id" json:"permission_id"`
	Effect       PolicyEffect    `db:"effect" json:"effect"`
	Priority     sql.NullInt32   `db:"priority" json:"priority"`
	Active       sql.NullBool    `db:"active" json:"active"`
	Conditions   json.RawMessage `db:"conditions" json:"conditions"`
	CreatedAt    sql.NullTime    `db:"created_at" json:"created_at"`
}

type Relation struct {
	ID        uuid.UUID     `db:"id" json:"id"`
	Type      RelationTypes `db:"type" json:"type"`
	Name      string        `db:"name" json:"name"`
	CreatedAt sql.NullTime  `db:"created_at" json:"created_at"`
}

type Role struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID    `db:"role_id" json:"role_id"`
	PermissionID uuid.UUID    `db:"permission_id" json:"permission_id"`
	CreatedAt    sql.NullTime `db:"created_at" json:"created_at"`
}

type Scope struct {
	Path      string       `db:"path" json:"path"`
	Method    string       `db:"method" json:"method"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type Session struct {
	ID               uuid.UUID             `db:"id" json:"id"`
	UserID           uuid.UUID             `db:"user_id" json:"user_id"`
	DeviceID         uuid.UUID             `db:"device_id" json:"device_id"`
	DeviceName       sql.NullString        `db:"device_name" json:"device_name"`
	DeviceType       NullSessionDeviceType `db:"device_type" json:"device_type"`
	IpAddress        pqtype.Inet           `db:"ip_address" json:"ip_address"`
	UserAgent        sql.NullString        `db:"user_agent" json:"user_agent"`
	FcmToken         sql.NullString        `db:"fcm_token" json:"fcm_token"`
	RefreshTokenHash sql.NullString        `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        time.Time             `db:"expires_at" json:"expires_at"`
	LastActivity     time.Time             `db:"last_activity" json:"last_activity"`
	Revoked          bool                  `db:"revoked" json:"revoked"`
	CreatedAt        time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time             `db:"updated_at" json:"updated_at"`
	Os               sql.NullString        `db:"os" json:"os"`
	OsVersion        sql.NullString        `db:"os_version" json:"os_version"`
	Browser          sql.NullString        `db:"browser" json:"browser"`
	BrowserVersion   sql.NullString        `db:"browser_version" json:"browser_version"`
}

type SiteSetting struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Key         string         `db:"key" json:"key"`
	Value       sql.NullString `db:"value" json:"value"`
	ValueType   string         `db:"value_type" json:"value_type"`
	Category    string         `db:"category" json:"category"`
	Description sql.NullString `db:"description" json:"description"`
	IsPublic    sql.NullBool   `db:"is_public" json:"is_public"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type SystemError struct {
	ID          uuid.UUID             `db:"id" json:"id"`
	Code        string                `db:"code" json:"code"`
	Message     string                `db:"message" json:"message"`
	StackTrace  sql.NullString        `db:"stack_trace" json:"stack_trace"`
	Metadata    pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	Severity    string                `db:"severity" json:"severity"`
	ServiceName sql.NullString        `db:"service_name" json:"service_name"`
	RequestID   uuid.NullUUID         `db:"request_id" json:"request_id"`
	UserID      uuid.NullUUID         `db:"user_id" json:"user_id"`
	IpAddress   pqtype.Inet           `db:"ip_address" json:"ip_address"`
	Path        sql.NullString        `db:"path" json:"path"`
	Method      sql.NullString        `db:"method" json:"method"`
	IsResolved  sql.NullBool          `db:"is_resolved" json:"is_resolved"`
	ResolvedAt  sql.NullTime          `db:"resolved_at" json:"resolved_at"`
	ResolvedBy  uuid.NullUUID         `db:"resolved_by" json:"resolved_by"`
	CreatedAt   time.Time             `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	RoleID       uuid.NullUUID  `db:"role_id" json:"role_id"`
	Username     sql.NullString `db:"username" json:"username"`
	Email        sql.NullString `db:"email" json:"email"`
	Phone        sql.NullString `db:"phone" json:"phone"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	Salt         sql.NullString `db:"salt" json:"salt"`
	Active       sql.NullBool   `db:"active" json:"active"`
	LastSeen     sql.NullTime   `db:"last_seen" json:"last_seen"`
	DeletedAt    sql.NullInt64  `db:"deleted_at" json:"deleted_at"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
	IsApproved   sql.NullBool   `db:"is_approved" json:"is_approved"`
}

type UserAttribute struct {
	UserID    uuid.UUID      `db:"user_id" json:"user_id"`
	Key       string         `db:"key" json:"key"`
	Value     sql.NullString `db:"value" json:"value"`
	CreatedAt sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type UserRelation struct {
	UserID     uuid.UUID    `db:"user_id" json:"user_id"`
	RelationID uuid.UUID    `db:"relation_id" json:"relation_id"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
}
