// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type SessionDeviceType string

const (
	SessionDeviceTypeDESKTOP SessionDeviceType = "DESKTOP"
	SessionDeviceTypeMOBILE  SessionDeviceType = "MOBILE"
	SessionDeviceTypeTABLET  SessionDeviceType = "TABLET"
	SessionDeviceTypeBOT     SessionDeviceType = "BOT"
	SessionDeviceTypeTV      SessionDeviceType = "TV"
)

func (e *SessionDeviceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionDeviceType(s)
	case string:
		*e = SessionDeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionDeviceType: %T", src)
	}
	return nil
}

type NullSessionDeviceType struct {
	SessionDeviceType SessionDeviceType `json:"session_device_type"`
	Valid             bool              `json:"valid"` // Valid is true if SessionDeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionDeviceType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionDeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionDeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionDeviceType), nil
}

type Session struct {
	ID           uuid.UUID             `db:"id" json:"id"`
	TuronID      int64                 `db:"turon_id" json:"turon_id"`
	DeviceID     uuid.UUID             `db:"device_id" json:"device_id"`
	DeviceName   sql.NullString        `db:"device_name" json:"device_name"`
	DeviceType   NullSessionDeviceType `db:"device_type" json:"device_type"`
	IpAddress    pqtype.Inet           `db:"ip_address" json:"ip_address"`
	UserAgent    sql.NullString        `db:"user_agent" json:"user_agent"`
	FcmToken     sql.NullString        `db:"fcm_token" json:"fcm_token"`
	ExpiresAt    time.Time             `db:"expires_at" json:"expires_at"`
	LastActivity time.Time             `db:"last_activity" json:"last_activity"`
	CreatedAt    time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time             `db:"updated_at" json:"updated_at"`
	Revoked      bool                  `db:"revoked" json:"revoked"`
}

type User struct {
	ID           int64          `db:"id" json:"id"`
	Username     sql.NullString `db:"username" json:"username"`
	Phone        string         `db:"phone" json:"phone"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	Salt         sql.NullString `db:"salt" json:"salt"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullInt64  `db:"deleted_at" json:"deleted_at"`
	LastSeen     sql.NullTime   `db:"last_seen" json:"last_seen"`
}
