// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    phone,
    password_hash,
    salt,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, username, phone, password_hash, salt, created_at, updated_at, deleted_at, last_seen
`

type CreateUserParams struct {
	Username     sql.NullString `db:"username" json:"username"`
	Phone        string         `db:"phone" json:"phone"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	Salt         sql.NullString `db:"salt" json:"salt"`
	CreatedAt    sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Phone,
		arg.PasswordHash,
		arg.Salt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = $2, updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type DeleteUserParams struct {
	ID        int64         `db:"id" json:"id"`
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.ID, arg.DeletedAt)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, username, phone, password_hash, salt, created_at, updated_at, deleted_at, last_seen FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

// PostgreSQL schema for user management with sqlc
// This file will be used by sqlc to generate type-safe Go code
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastSeen,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, phone, password_hash, salt, created_at, updated_at, deleted_at, last_seen FROM users
WHERE phone = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastSeen,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, phone, password_hash, salt, created_at, updated_at, deleted_at, last_seen FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Phone,
			&i.PasswordHash,
			&i.Salt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users
SET last_seen = $2
WHERE id = $1
`

type UpdateLastSeenParams struct {
	ID       int64        `db:"id" json:"id"`
	LastSeen sql.NullTime `db:"last_seen" json:"last_seen"`
}

func (q *Queries) UpdateLastSeen(ctx context.Context, arg UpdateLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, arg.ID, arg.LastSeen)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET 
    username = COALESCE($2, username),
    phone = COALESCE($3, phone),
    password_hash = COALESCE($4, password_hash),
    salt = COALESCE($5, salt),
    updated_at = $6
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	ID           int64          `db:"id" json:"id"`
	Username     sql.NullString `db:"username" json:"username"`
	Phone        string         `db:"phone" json:"phone"`
	PasswordHash string         `db:"password_hash" json:"password_hash"`
	Salt         sql.NullString `db:"salt" json:"salt"`
	UpdatedAt    sql.NullTime   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Phone,
		arg.PasswordHash,
		arg.Salt,
		arg.UpdatedAt,
	)
	return err
}
