// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteUserAttribute(ctx context.Context, arg DeleteUserAttributeParams) error
	// PostgreSQL schema for user management with sqlc
	// This file will be used by sqlc to generate type-safe Go code
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserAttributes(ctx context.Context, userID uuid.UUID) ([]GetUserAttributesRow, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SetUserAttribute(ctx context.Context, arg SetUserAttributeParams) error
	UpdateLastSeen(ctx context.Context, arg UpdateLastSeenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
