package consts

const (
	HeaderAuthorization                 = "Authorization"
	HeaderXRequestID                    = "X-Request-ID"
	HeaderXDeviceID                     = "X-Device-ID"
	HeaderXAPIKey                       = "X-API-KEY"
	HeaderXForwardedProto               = "X-Forwarded-Proto"
	HeaderOrigin                        = "Origin"
	HeaderUserAgent                     = "User-Agent"
	HeaderAcceptLanguage                = "Accept-Language"
	HeaderLanguage                      = "Language"
	HeaderXApiKeyType                   = "X-Api-Key-Type"
	HeaderAppVersion                    = "appVersion"
	HeaderContentType                   = "Content-Type"
	HeaderXTotalCount                   = "X-Total-Count"
	HeaderXCSRFToken                    = "X-CSRF-Token"
	HeaderCacheControl                  = "Cache-Control"
	HeaderXRequestedWith                = "X-Requested-With"
	HeaderXContentTypeOptions           = "X-Content-Type-Options"
	HeaderXFrameOptions                 = "X-Frame-Options"
	HeaderXXSSProtection                = "X-XSS-Protection"
	HeaderReferrerPolicy                = "Referrer-Policy"
	HeaderXPermittedCP                  = "X-Permitted-Cross-Domain-Policies"
	HeaderCSP                           = "Content-Security-Policy"
	HeaderHSTS                          = "Strict-Transport-Security"
	HeaderSecFetchSite                  = "Sec-Fetch-Site"
	HeaderSecFetchMode                  = "Sec-Fetch-Mode"
	HeaderSecFetchDest                  = "Sec-Fetch-Dest"
	HeaderAccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	HeaderAccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	HeaderAccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	HeaderAccessControlAllowMethods     = "Access-Control-Allow-Methods"
	HeaderAccessControlMaxAge           = "Access-Control-Max-Age"
	HeaderAccessControlExposeHeaders    = "Access-Control-Expose-Headers"
)

const (
	HeaderValueNoSniff      = "nosniff"
	HeaderValueDeny         = "DENY"
	HeaderValueXSSBlock     = "1; mode=block"
	HeaderValueStrictOrigin = "strict-origin-when-cross-origin"
	HeaderValueNone         = "none"
	HeaderValueHSTS         = "max-age=31536000; includeSubDomains; preload"
	HeaderValueSameOrigin   = "same-origin"
	HeaderValueSameSite     = "same-site"
	HeaderValueNavigate     = "navigate"
	HeaderValueDocument     = "document"
)
