// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: v1/common/pagination.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination represents pagination parameters
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_v1_common_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_common_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_v1_common_pagination_proto protoreflect.FileDescriptor

const file_v1_common_pagination_proto_rawDesc = "" +
	"\n" +
	"\x1av1/common/pagination.proto\x12\agrpc.v1\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offsetB&Z$gct/docs/protobuf/genproto/v1/commonb\x06proto3"

var (
	file_v1_common_pagination_proto_rawDescOnce sync.Once
	file_v1_common_pagination_proto_rawDescData []byte
)

func file_v1_common_pagination_proto_rawDescGZIP() []byte {
	file_v1_common_pagination_proto_rawDescOnce.Do(func() {
		file_v1_common_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_pagination_proto_rawDesc), len(file_v1_common_pagination_proto_rawDesc)))
	})
	return file_v1_common_pagination_proto_rawDescData
}

var file_v1_common_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_common_pagination_proto_goTypes = []any{
	(*Pagination)(nil), // 0: grpc.v1.Pagination
}
var file_v1_common_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_common_pagination_proto_init() }
func file_v1_common_pagination_proto_init() {
	if File_v1_common_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_pagination_proto_rawDesc), len(file_v1_common_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_pagination_proto_goTypes,
		DependencyIndexes: file_v1_common_pagination_proto_depIdxs,
		MessageInfos:      file_v1_common_pagination_proto_msgTypes,
	}.Build()
	File_v1_common_pagination_proto = out.File
	file_v1_common_pagination_proto_goTypes = nil
	file_v1_common_pagination_proto_depIdxs = nil
}
